name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        run: npm run postinstall

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          nohup node .output/server/index.mjs &
          echo $! > server.pid
          sleep 2

      - name: Smoke test /api/health
        run: |
          STATUS=$(curl -s -o /tmp/health.json -w "%{http_code}" http://localhost:3000/api/health)
          if [ "$STATUS" != "200" ]; then
            echo "Unexpected status: $STATUS"; cat /tmp/health.json; exit 1;
          fi
          test -s /tmp/health.json || (echo "Empty response" && exit 1)
          echo "OK: $(cat /tmp/health.json)"

      - name: Stop server
        if: always()
        run: |
          kill -9 $(cat server.pid) || true
